//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StadiumApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int Id { get; set; }
        public int ContactId { get; set; }
        public int StadiumId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public decimal Price { get; set; }
        public bool IsPlayed { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Stadiums Stadiums { get; set; }
    }
}
